src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article

{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     * @Gedmo\Slug(fields={"title"})
     */
    //@Gedmo\Slug(fields={"title"})
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="integer")
     */
    private $heartCount = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="update")

     */
    private $updateAt;

    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string

    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }


    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getHeartCount(): ?int
    {
        return $this->heartCount;
    }

    public function setHeartCount(int $heartCount): self
    {
        $this->heartCount = $heartCount;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }
    public function getImagePath(){
        return 'images/'.$this->getImageFilename();
    }
    public function incrementHeartCount(): self
    {
        $this->heartCount = $this -> heartCount + 1;
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->updateAt;
    }

    public function setUpdateAt(\DateTimeInterface $updateAt): self
    {
        $this->updateAt = $updateAt;

        return $this;
    }
}

src/Controller/ArticleAdminController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ArticleAdminController extends AbstractController
{
    /**
     * @Route("/admin/article/new")
     */
    public function new(EntityManagerInterface $em){
        die('todo');
        $article = new Article();
        $article->setTitle('Why Asteroid Taste Like Bacon')
            ->setSlug('why-asteroid-taste-like-bacon-'.rand(100,999))
            ->setContent(<<<EOF
Spicy **jalapeno bacon** ipsum dolor amet veniam shank in dolore. Ham hock nisi landjaeger cow,
lorem proident [beef ribs](https://baconipsum.com/) aute enim veniam ut cillum pork chuck picanha. Dolore reprehenderit
labore minim pork belly spare ribs cupim short loin in. Elit exercitation eiusmod dolore cow
**turkey** shank eu pork belly meatball non cupim.
Laboris beef ribs fatback fugiat eiusmod jowl kielbasa alcatra dolore velit ea ball tip. Pariatur
laboris sunt venison, et laborum dolore minim non meatball. Shankle eu flank aliqua shoulder,
capicola biltong frankfurter boudin cupim officia. Exercitation fugiat consectetur ham. Adipisicing
picanha shank et filet mignon pork belly ut ullamco. Irure velit turducken ground round doner incididunt
occaecat lorem meatball prosciutto quis strip steak.
Meatball adipisicing ribeye bacon strip steak eu. Consectetur ham hock pork hamburger enim strip steak
mollit quis officia meatloaf tri-tip swine. Cow ut reprehenderit, buffalo incididunt in filet mignon
strip steak pork belly aliquip capicola officia. Labore deserunt esse chicken lorem shoulder tail consectetur
cow est ribeye adipisicing. Pig hamburger pork belly enim. Do porchetta minim capicola irure pancetta chuck
fugiat.
EOF
            );
        // PUBLISH MOST ARTICLES
        if (rand(1,10) > 2){
            $article->setPublishedAt(new \DateTime(sprintf('-%d days', rand(1, 100))));
        }
        $article->setAuthor('Mike Ferengi')
            ->setHeartCount(rand(5, 100))
            ->setImageFilename('asteroid.jpeg');
        $em-> persist($article);
        $em->flush();
        return new Response(sprintf(
            'Hiya! New Article id: #%d slug: %s',
            $article->getId(),
            $article->getSlug()
        ));
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Repository\ArticleRepository;
use App\Services\SlackClient;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;


class ArticleController extends AbstractController
{
    private $isDebug;

    public function __construct($isDebug = true)
    {
        $this->isDebug = $isDebug;
    }

    /**
     * @Route("/", name = "app_homepage")
     */
    public function homepage(ArticleRepository $repository)
    {
        $articles = $repository->findAllPublishedOrderedByNewest();
        return $this->render('article/homepage.html.twig', [
            'articles' => $articles
        ]);
    }

    /**
     * @Route("/news/{slug}", name="article_show")
     */
    public function show(Article $article, SlackClient $slack)
    {
        if ($article->getSlug() == 'khaaaaaan') {
            $slack->sendMessage('Usuario', 'Hola este es un mensaje desde praga!!');
        }

        $comments = [
            'I ate a normal rock once. It did NOT taste like bacon!',
            'Woohoo! I\'m going on an all-asteroid diet!',
            'I like bacon too! Buy some from my site! bakinsomebacon.com',
        ];

        return $this->render('article/show.html.twig', [
            'article' => $article,
            'comments' => $comments,
        ]);
    }

    /**
     * @Route("/news/{slug}/heart", name="article_toggle_heart", methods={"POST"})
     */
    public function toggleArticleHeart(Article $article, LoggerInterface $logger, EntityManagerInterface $em ){
        $article -> incrementHeartCount();
        $em->flush();
        $logger -> info('Article is begin hearted');
        return new JsonResponse(['hearts' => $article->getHeartCount()]);
    }

}

templates/article/homepage.html.twig
{% extends '/base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">

            <!-- Article List -->

            <div class="col-sm-12 col-md-8">

                <!-- H1 Article -->
                <a class="main-article-link" href="#">
                    <div class="main-article mb-5 pb-3">
                        <img src="{{ asset('images/meteor-shower.jpg') }}" alt="meteor shower">
                        <h1 class="text-center mt-2">Ursid Meteor Shower: <br>Healthier than a regular shower?</h1>
                    </div>
                </a>

                <!-- Supporting Articles -->
                {% for article in articles %}

                <div class="article-container my-1">
                    <a href="{{ path('article_show',{ slug: article.slug }) }}">
                        <img class="article-img" src="{{ asset( article.imagePath) }}">
                        <div class="article-title d-inline-block pl-3 align-middle">
                            <span>{{ article.title }}</span>
                            <br>
                            <span class="align-left article-details"><img class="article-author-img rounded-circle" src="{{ asset('images/alien-profile.png') }}"> {{ article.author }} </span>
                            <span class="pl-5 article-details float-right">
                                {{ article.publishedAt ? article.publishedAt | ago }}
                            </span>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>

            <!-- Right bar ad space -->


            <div class="col-sm-12 col-md-4 text-center">
                <div class="ad-space mx-auto mt-1 pb-2 pt-2">
                    <img class="advertisement-img" src="{{ asset('images/space-ice.png') }}">
                    <p><span class="advertisement-text">New:</span> Space Ice Cream!</p>
                    <button class="btn btn-info">Buy Now!</button>
                </div>

                <div class="quote-space pb-2 pt-2 px-5">
                    <h3 class="text-center pb-3">Trending Quotes</h3>
                    <p><i class="fa fa-comment"></i> "Our two greatest problems are gravity and paperwork. We can lick gravity, but sometimes the paperwork is overwhelming." <br>— <a href="https://en.wikipedia.org/wiki/Wernher_von_Braun">Wernher von Braun, Rocket Engineer</a></p>

                    <p class="pt-4"><i class="fa fa-comment"></i> "Let's face it, space is a risky business. I always considered every launch a barely controlled explosion." <br>— <a href="https://en.wikipedia.org/wiki/Aaron_Cohen_(Deputy_NASA_administrator)">Aaron Cohen, NASA Administrator</a></p>

                    <p class="pt-4"><i class="fa fa-comment"></i> "If offered a seat on a rocket ship, don't ask what seat. Just get on."<br>— <a href="https://en.wikipedia.org/wiki/Christa_McAuliffe">Christa McAuliffe, Challenger Astronaut</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}Read: {{ article.title }}{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="show-article-container p-3 mt-4">
                    <div class="row">
                        <div class="col-sm-12">
                            <img class="show-article-img" src="{{ asset('images/asteroid.jpeg') }}">
                            <div class="show-article-title-container d-inline-block pl-3 align-middle">

                                <span class="show-article-title ">{{ article.title }}</span>

                                <br>
                                <span class="align-left article-details"><img class="article-author-img rounded-circle"
                                                                              src="{{ asset('images/alien-profile.png') }}"> {{ article.author }} </span>
                                <span class="pl-2 article-details">
                                    {{ article.publishedAt ? article.publishedAt | ago : 'unpublished'}}
                                </span>
                                <span class="pl-2 article-details">
                                <span class="js-like-article-count">{{ article.heartCount }}</span>

                                <a href="{{ path('article_toggle_heart', {slug: article.slug}) }}"
                                   class="fa fa-heart-o like-article js-like-article"></a>

                            </span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="article-text">

                                {{ article.content | cached_markdown }}

                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <p class="share-icons mb-5"><span class="pr-1">Share:</span> <i
                                        class="pr-1 fa fa-facebook-square"></i><i class="pr-1 fa fa-twitter-square"></i><i
                                        class="pr-1 fa fa-reddit-square"></i><i class="pr-1 fa fa-share-alt-square"></i>
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <h3><i class="pr-3 fa fa-comment"></i>{{ comments|length }} Comments</h3>
                            <hr>

                            <div class="row mb-5">
                                <div class="col-sm-12">
                                    <img class="comment-img rounded-circle"
                                         src="{{ asset('images/astronaut-profile.png') }}">
                                    <div class="comment-container d-inline-block pl-3 align-top">
                                        <span class="commenter-name">Amy Oort</span>
                                        <div class="form-group">
                                            <textarea class="form-control comment-form" id="articleText"
                                                      rows="1"></textarea>
                                        </div>
                                        <button type="submit" class="btn btn-info">Comment</button>
                                    </div>
                                </div>
                            </div>

                            {% for comment in comments %}
                                <div class="row">
                                    <div class="col-sm-12">
                                        <img class="comment-img rounded-circle"
                                             src="{{ asset('images/alien-profile.png') }}">
                                        <div class="comment-container d-inline-block pl-3 align-top">
                                            <span class="commenter-name">Mike Ferengi</span>
                                            <br>
                                            <span class="comment"> {{ comment }}</span>
                                            <p><a href="#">Reply</a></p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}


{% block javascripts %}
    {{ parent() }}

    <script src="{{ asset('js/article_show.js') }}"></script>
{% endblock %}

templates/base.html.twig
<!doctype html>
<html lang="en">

<head>
    <title>{% block title %}Welcome to the SpaceBar{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block stylesheets %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
        <link rel="stylesheet" href= "/css/font-awesome.css">
        <link rel="stylesheet" href= "/css/styles.css">
    {% endblock %}
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark navbar-bg mb-5">
    <a style="margin-left: 75px;" class="navbar-brand space-brand" href="{{ path('app_homepage') }}">The Space Bar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a style="color: #fff;" class="nav-link" href="#">Local Asteroids</a>
            </li>
            <li class="nav-item">
                <a style="color: #fff;" class="nav-link" href="#">Weather</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-info my-2 my-sm-0" type="submit">Search</button>
        </form>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown" style="margin-right: 75px;">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="nav-profile-img rounded-circle" src="{{ asset('images/astronaut-profile.png') }}">
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Profile</a>
                    <a class="dropdown-item" href="#">Create Post</a>
                    <a class="dropdown-item" href="#">Logout</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

{% block body %}{% endblock %}

<footer class="footer">
    <div class="container text-center">
        <span class="text-muted">Made with <i class="fa fa-heart" style="color: red;"></i> by the guys and gals at <a
                    href="https://knpuniversity.com">KnpUniversity</a></span>
    </div>
</footer>


{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
            integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
            integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
            crossorigin="anonymous"></script>
    <script>
        $('.dropdown-toggle').dropdown();
    </script>
{% endblock %}
</body>
</html>